language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - '$HOME/.m2/repository'

script:
  - mvn clean test

after_success:
  - mvn clean package

#branches:
#  only:
#    - test
notifications:
  email: true
