language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - '$HOME/.m2/repository'

script:
  - mvn clean package -DskipTests=true

after_success:
  - mvn -o site
  - mvn -o site-deploy

#branches:
#  only:
#    - test
notifications:
  email: true
