logging:
    config: classpath:config/logback-spring.xml


mybatis:
    configuration:
        local-cache-scope: session
        map-underscore-to-camel-case: true
        use-generated-keys: true


pagehelper:
    reasonable: true
    support-methods-arguments: true


spring:
    datasource:
        data: classpath:db/data.sql
        schema: classpath:db/schema.sql
        url: jdbc:mysql://local-dev:3306/druid_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 15
            auto-commit: true
            idle-timeout: 10000
            pool-name: HikariCP_Demo
            max-lifetime: 30000
            connection-test-query: select 1
            connection-timeout: 1000
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: true
                web-allow-others: true
    jackson:
        property-naming-strategy: SNAKE_CASE
