server:
  jetty:
    accesslog:
      enabled: true
      date-format: yyyy/mm/dd hh:mm:ss

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

org:
  laidu:
    learn:
      spring:
        mvc:
          properties:
            MvcCProperties:
              logbackUuid: _uuid
              appName: Demo

