server:
  jetty:
    accesslog:
      enabled: false
      date-format: yyyy/mm/dd hh:mm:ss

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
  application:
    name: mvc

mvc:
  logbackUuid: "_uuid"
  appName: "demo"
monitor:
  log-path: logs/
  log-type: monitor

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level.org.zalando.logbook: TRACE

logbook:
  exclude:
  - /health
  - /admin/**
  filter.enabled: true
  format.style: json
  obfuscate:
    headers:
    - Authorization
    - X-Secret
    parameters:
    - access_token
    - password
  write:
    category: http.wire-log
    level: INFO
    chunk-size: 1000

storage:
  location: ${user.home}/temp/resource
