spring:
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  boot:
    admin:
      client:
        enabled: true
        auto-registration: true
        url: "http://localhost:2222"
        api-path: instances
      ui:
        cache:
          no-store: true

management:
  server:
    port: 9998
    address: localhost
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  # METRICS
  metrics:
    export:
      atlas:
        enabled: true
        step: 1s
      graphite:
        host: localhost
        port: 2004
        enabled: true
        step: 1s
        protocol: pickled
    binders:
      jvm:
        enabled: true
server:
  port: 2222
