spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  boot:
    admin:
      client:
        enabled: true
        auto-registration: true
        url: "http://localhost:2222"
        api-path: instances
      ui:
        cache:
          no-store: true
      notify:
        mail:
          to: tiancai.zang@finlink.net.cn
          from: laidu823@sina.com
  mail:
    host: smtp.sina.com
    username: laidu823@sina.com
    password: ${sina_password} # 通过环境变量获取
    default-encoding: utf-8
    port: 465
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: false
            enable: false
          ssl:
            enable: true


management:
  server:
    port: 9998
    address: localhost
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  # METRICS
  metrics:
    export:
      atlas:
        enabled: true
        step: 1s
      graphite:
        host: localhost
        port: 2004
        enabled: true
        step: 1s
        protocol: pickled
    binders:
      jvm:
        enabled: true
server:
  port: 2222
