spring:
  boot:
    admin:
      client:
        url: http://localhost:2222
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  application:
    name: spring-boot-app-1
    admin:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:

        include: "*"
    web:
      exposure:
        include: "*"
  # METRICS
  metrics:
    export:
      atlas:
        enabled: true
        step: 1s
    binders:
      jvm:
        enabled: true
