
spring:
  boot:
    admin:
      client:
        enabled: true
        auto-registration: true
        url: "http://local-dev:8761"
        api-path: instances
      ui:
        cache:
          no-store: true
      notify:
        mail:
          to: tiancai.zang@finlink.net.cn
          from: laidu823@sina.com
  mail:
    host: smtp.sina.com
    username: laidu823@sina.com
    password: ${sina_password} # 通过环境变量获取
    default-encoding: utf-8
    port: 465
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: false
            enable: false
          ssl:
            enable: true

eureka:
  instance:
    hostname: local-dev
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  server:
    port: 9999
    address: local-dev
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
server:
  port: 1111
